#!/bin/bash
# Vim configuration

git clone https://github.com/Mslef/vim-dotfiles.git ~/.vim/vim-dotfiles
mv ~/.vim/vim-dotfiles/.vimrc ~/.vimrc
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
vim +PluginInstall +qall

